In [9]:
import pandas as pd
dataset = pd.read_csv('visit_log.csv',sep = ';')
def source(data):
    if data['traffic_source'] == 'yandex' or data['traffic_source'] == 'google':
        return 'organic'
    if data['traffic_source'] == 'paid' or data['traffic_source'] == 'email':
        if data['region'] == 'Russia':
            return 'ad'
        return 'other'
    return data['traffic_source']
dataset['source_type'] = dataset.apply(source, axis = 1)
dataset

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,organic
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,organic
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,organic
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,organic
...,...,...,...,...,...,...,...
18933,1550094288,57e5ba8560,https://host.ru/c2382eb3d6afc8d0f3,Belarus,98b19810d0,paid,other
18934,1550094296,6f9389ec1b,https://host.ru/f1eb4601740d627ab0,Russia,32ebb20c13,paid,ad
18935,1550094308,e8cf2eb8e6,https://host.ru/a5dda93e70318570c0,Belarus,b85baa8c73,yandex,organic
18936,1550094314,79530b9a67,https://host.ru/6fda01ec57f23abc9e,Russia,e154b06121,paid,ad
18937,1550094323,b3b634f824,https://host.ru/39fa884393666d45fc,Russia,7d27a58fb8,email,ad

In [73]:
text = pd.read_csv('URLs.txt')
import re 
def filter(text):
     return text.str.contains('[/]\d{8}[-]', regex = True)
text["filtered"] = text.apply(filter, axis = 1)
text.head(20)

                                                  url  filtered
0                                             /world/     False
1                                            /latest/     False
2                                       /?updated=top     False
3   /politics/36188461-s-marta-zhizn-rossiyan-susc...      True
4   /world/36007585-tramp-pridumal-kak-reshit-ukra...      True
5   /science/36157853-nasa-sobiraet-ekstrennuyu-pr...      True
6   /video/36001498-poyavilis-pervye-podrobnosti-g...      True
7   /world/36007585-tramp-pridumal-kak-reshit-ukra...      True
8                                           /science/     False
9                                             /sport/     False
10  /middleeast/36131117-divizion-s-400-ne-zametil...      True
11  /economics/36065674-rossiyane-vozmutilis-minim...      True
12  /politics/36118047-otets-24-detey-potreboval-i...      True
13  /travel/36194479-v-sheremetevo-passazhiry-ustr...      True
14  /politics/35638742-nesolidno-mariya-zaharova-s...      True
15  /video/36012692-tramp-otkrestilsya-ot-rossii-i...      True
16     /starlife/36174817-guzeeva-rasstalas-s-muzhem/      True
17  /health/36149308-predlozheno-prostoe-sredstvo-...      True
18  /science/36139723-set-vzbudorazhila-novost-o-s...      True
19  /cis/36229699-poroshenko-obyavil-vseukrainskiy...      True

In [120]:
data = pd.read_csv('ratings.csv')
k = data.groupby('userId').filter(lambda g: len(g) > 100).groupby('userId').agg({'timestamp':['max' ,'min']})
k['timestamp']['max'].sub(k['timestamp']['min'],axis = 0).head(5)

userId
4        203560
8         85187
15    471393496
17         8053
19         5282
dtype: int64

In [140]:
rzd = pd.DataFrame(
    {
        'client_id': [111, 112, 113, 114, 115],
        'rzd_revenue': [1093, 2810, 10283, 5774, 981]
    }
)
auto = pd.DataFrame(
    {
        'client_id': [113, 114, 115, 116, 117],
        'auto_revenue': [57483, 83, 912, 4834, 98]
    }
)
air = pd.DataFrame(
    {
        'client_id': [115, 116, 117, 118],
        'air_revenue': [81, 4, 13, 173]
    }
)
client_base = pd.DataFrame(
    {
        'client_id': [111, 112, 113, 114, 115, 116, 117, 118],
        'address': ['Комсомольская 4', 'Энтузиастов 8а', 'Левобережная 1а', 'Мира 14', 'ЗЖБИиДК 1', 
                    'Строителей 18', 'Панфиловская 33', 'Мастеркова 4']
    }
)
first = rzd.merge(auto, how = 'outer').merge(air, how ='outer')
second =  rzd.merge(auto, how = 'outer').merge(air, how ='outer').merge(client_base, how = 'inner')
print(first)
print(second)

   client_id  rzd_revenue  auto_revenue  air_revenue
0        111       1093.0           NaN          NaN
1        112       2810.0           NaN          NaN
2        113      10283.0       57483.0          NaN
3        114       5774.0          83.0          NaN
4        115        981.0         912.0         81.0
5        116          NaN        4834.0          4.0
6        117          NaN          98.0         13.0
7        118          NaN           NaN        173.0
   client_id  rzd_revenue  auto_revenue  air_revenue          address
0        111       1093.0           NaN          NaN  Комсомольская 4
1        112       2810.0           NaN          NaN   Энтузиастов 8а
2        113      10283.0       57483.0          NaN  Левобережная 1а
3        114       5774.0          83.0          NaN          Мира 14
4        115        981.0         912.0         81.0        ЗЖБИиДК 1
5        116          NaN        4834.0          4.0    Строителей 18
6        117          NaN          98.0         13.0  Панфиловская 33
7        118          NaN           NaN        173.0     Мастеркова 4